Fix reading no headers
CommunityHiQ/Frends.Community.RabbitMQ pull request #27
Opened 2022-07-26 06:51 UTC by levik-buka

May be it is a bug in RabbitMQ Client library, but when publishing messages without headers in RabbitMQ Management UI,
basicProperties.IsHeadersPresent() returns true, but basicProperties.Headers is null.

Also added check if header is null or non byte[] type.

2023-03-30 09:28 UTC, RikuVirtanen requested changes
Some indentations where wrong but otherwise looking good. Please add some test to indicate that the bug is fixed.

2023-03-30 09:28 UTC, RikuVirtanen commented on Frends.Community.RabbitMQ.Tests/UnitTests.cs
> +        {
Incorrect indentation.

2023-03-30 09:28 UTC, RikuVirtanen commented on Frends.Community.RabbitMQ.Tests/UnitTests.cs
> +        {
Incorrect indentation.

2023-03-30 09:28 UTC, RikuVirtanen commented on Frends.Community.RabbitMQ/RabbitMQTask.cs
> +                  }).ToList()
Incorrect indentation.

2023-04-03 09:13 UTC, levik-buka commented
I don't understand why, but I can not reproduce "basicProperties.IsHeadersPresent() returns true, but basicProperties.Headers is null" error any more.

2023-04-03 09:13 UTC, closed without merging